export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body>
        <header>default header </header>
        {children}
        <footer>default footer </footer>
  
      </body>
      
    </html>
  )
}
